name: .NET build + deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: ./MyPhotoDreamApp
      run: dotnet restore
    - name: Build
      working-directory: ./MyPhotoDreamApp
      run: dotnet build --no-restore
    - name: Dotnet Publish
      working-directory: ./MyPhotoDreamApp
      run: dotnet publish -c Release -o deploy
    - name: rsync deploy
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: /home/runner/work/MyPhotoDreamApp/MyPhotoDreamApp/MyPhotoDreamApp/deploy/
        remote_path: ${{ secrets.REMOTE_TARGET }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.REMOTE_SSH_KEY }}
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo systemctl restart kestrel-MyPhotoDreamApp.service
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
