name: .NET build + deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: ./MyPhotoDreamApp
      run: dotnet restore
    - name: Build
      working-directory: ./MyPhotoDreamApp
      run: dotnet build --no-restore
    - name: Dotnet Publish
      working-directory: ./MyPhotoDreamApp
      run: dotnet publish -c Release -o deploy
    - name: Run SSH command 0
      uses: garygrossgarten/github-action-ssh@v0.8.0
      with:
        command: sudo chown -R admin:www /home/www/
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.9.0
      with:
        local: /home/runner/work/MyPhotoDreamApp/MyPhotoDreamApp/MyPhotoDreamApp/deploy/
        remote: ${{ secrets.REMOTE_TARGET }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
        concurrency: 4
        atomicPut: false
    - name: Run SSH command 1
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo chown -R www:admin /home/www/
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
    - name: Run SSH command 2
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo systemctl restart kestrel-MyPhotoDreamApp.service
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
